# Generated by Django 3.0 on 2021-12-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='years',
            new_name='yearsschool',
        ),
    ]
