# Generated by Django 3.0 on 2021-12-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0002_auto_20211207_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='levelschool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
